# BoladoBSPWM · touchpad (libinput)
# Click derecho con 2 dedos / central con 3 (en vez de esquinas).
Section "InputClass"
    Identifier        "touchpad"
    Driver            "libinput"
    MatchIsTouchpad   "on"
    Option "Tapping"           "on"            # tap para click
    Option "TappingButtonMap"  "lrm"           # 1 dedo=izq, 2=der, 3=central
    Option "ClickMethod"       "clickfinger"   # pulsar con 2 dedos = click derecho
    Option "NaturalScrolling"  "false"         # scroll tradicional (dedo abajo -> baja)
    Option "DisableWhileTyping" "on"
EndSection
