#!/bin/bash


rofi_command="rofi -theme ~/.config/rofi-mono.rasi -theme-str 'configuration { show-icons: false; location: 3; } window { width: 22%; x-offset: -30px; y-offset: 70px; } listview { lines: 5; } mainbox { children: [ listview ]; }'"


# Options
shutdown=" Shutdown"
reboot=" Restart"
lock=" Lock"
suspend=" Sleep"
logout=" Logout"

# Variable passed to rofi
options="$lock\n$suspend\n$logout\n$reboot\n$shutdown"

chosen="$(echo -e "$options" | $rofi_command -p "System" -dmenu -selected-row 0)"
case $chosen in
    $shutdown)
        systemctl poweroff
        ;;
    $reboot)
        systemctl reboot
        ;;
    $lock)
        i3lock
        ;;
    $suspend)
        systemctl suspend
        ;;
    $logout)
        kill -9 -1
        ;;
esac

