# BoladoBSPWM — web-greeter + tema Glorious
[greeter]
debug-mode          = false
detect-theme-errors = true
screensaver-timeout = 300
secure-mode         = true
time-language       = auto
webkit-theme        = glorious

[branding]
background-images   = /usr/share/backgrounds
logo                =
user-image          =
