[color]
;; Kanagawa Wave — paleta canónica
bg = #1F1F28
fg = #DCD7BA
ac = #957FB8
ac-fg = #16161D

trans = #00000000
white = #DCD7BA
black = #16161D

;; acentos kanagawa (para módulos custom)
sumi-ink   = #16161D
sumi-ink2  = #2A2A37
fuji-white = #DCD7BA
fuji-gray  = #727169
samurai-red    = #E82424
autumn-red     = #C34043
autumn-yellow  = #DCA561
carp-yellow    = #E6C384
autumn-green   = #76946A
spring-green   = #98BB6C
wave-aqua      = #6A9589
crystal-blue   = #7E9CD8
oni-violet     = #957FB8
sakura-pink    = #D27E99
ronin-yellow   = #FF9E3B
dragon-blue    = #658594
spring-blue    = #7FB4CA

;; aliases compatibles con resto del current.ini
red = #C34043
pink = #D27E99
purple = #957FB8
deep-purple = #957FB8
indigo = #658594
blue = #7E9CD8
light-blue = #7FB4CA
cyan = #6A9589
teal = #6A9589
green = #76946A
light-green = #98BB6C
lime = #98BB6C
yellow = #E6C384
amber = #DCA561
orange = #DCA561
deep-orange = #FF9E3B
brown = #54546D
gray = #727169
blue-gray = #2A2A37
